package cli

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	"gemini/ai"

	"github.com/charmbracelet/huh"
	"github.com/charmbracelet/lipgloss"
	"golang.org/x/term"
)

func Init(apiKey string) {
	var text string

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("prompt").
				Value(&text),
		),
	)

	err := form.Run()
	if err != nil {
		log.Fatal(err)
	}

	if strings.ToLower(text) == "bye" {
		fmt.Println("Goodbye!")
		os.Exit(0)
	}

	width, _, err := term.GetSize(int(os.Stdout.Fd()))
	if err != nil {
		log.Println("Error getting terminal size:", err)
		width = 80
	}
	ctx := context.Background()

	response, err := ai.GenerateContent(ctx, apiKey, text)
	if err != nil {
		log.Fatal("Error generating content:", err)
	}

	if len(response.Candidates) == 0 || len(response.Candidates[0].Content.Parts) == 0 {
		log.Fatal("No content generated by Gemini API.")
	}

	generatedText := response.Candidates[0].Content.Parts[0].Text

	style := lipgloss.NewStyle().
		BorderStyle(lipgloss.RoundedBorder()).
		BorderForeground(lipgloss.Color("63")).
		Padding(1, 2).
		Width(width - 4)

	output := fmt.Sprintf("Gemini:\n%s", generatedText)
	borderedOutput := style.Render(output)

	fmt.Println(borderedOutput)
}
